# Site settings
title: Hengshuai Yao
email: 
description: "Not a scientist yet."
baseurl: ""
url: "http://karpathy.github.io"
twitter_username: karpathy
github_username:  hengshuaiyao

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
